[
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Saving Rates",
    RateCode: "SANSV",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Savings Account for Senior Citizens - Sampath Sanhinda Saver",
    Comment: "An additional 0.25% for Sanhinda Saver (For USD)",
    ProductOrder: "7",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "6",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Saving Rates",
    RateCode: "MMSAV",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead:
      "Savings Account for High Value Transactions - Money Market Account",
    Comment: "An additional 0.25% for Sanhinda Saver (For USD)",
    ProductOrder: "8",
    SlabAmount: [
      {
        BeginSlbAmount: "0",
        EndSlbAmount: "499999.99",
        SlabPicture: "Day end balance < Rs.<END_SLAB_AMT>/-",
        PerAnumPercentage: "",
        Rate: "3",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Saving Rates",
    RateCode: "HITSV",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Savings Account with high interest - Hit Saver",
    Comment: "",
    ProductOrder: "2",
    SlabAmount: [
      {
        BeginSlbAmount: "0",
        EndSlbAmount: "49999.99",
        SlabPicture: "below Rs. <END_SLAB_AMT>",
        PerAnumPercentage: "",
        Rate: "3",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "50000",
        EndSlbAmount: "499999.99",
        SlabPicture: "Rs. <BEGIN_SLAB_AMT> to <END_SLAB_AMT>",
        PerAnumPercentage: "",
        Rate: "4.5",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999.99",
        SlabPicture: "Rs.<BEGIN_SLAB_AMT> ",
        PerAnumPercentage: "",
        Rate: "5.5",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Saving Rates",
    RateCode: "PUBU",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Sampath Pubudu Children's Savings Account",
    Comment: "",
    ProductOrder: "5",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "4.5",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Saving Rates",
    RateCode: "XSET",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Teen Savings Account - X Set",
    Comment: "",
    ProductOrder: "6",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "3",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Term Deposits  Rates",
    RateCode: "FDKC",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Sampath Kalin Cash Fixed Deposits",
    Comment: "Nominal rate is used for deposits.",
    ProductOrder: "10",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "0",
        MaxContractedMonths: "5",
        Period: "3",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "11.33",
        AerMat: "9.39",
        MatSchmCode: "",
        RateMon: "9",
        AerMon: "9.41",
        MonSchmCode: "",
        NominalRate: "7.36",
        NominalSchmCode: "",
        EffectiveRate: "7.71",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "5",
        MaxContractedMonths: "11",
        Period: "6",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "11.33",
        AerMat: "9.39",
        MatSchmCode: "",
        RateMon: "9",
        AerMon: "9.41",
        MonSchmCode: "",
        NominalRate: "7.71",
        NominalSchmCode: "",
        EffectiveRate: "8.16",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "11",
        MaxContractedMonths: "999",
        Period: "12",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "11.33",
        AerMat: "9.39",
        MatSchmCode: "",
        RateMon: "9",
        AerMon: "9.41",
        MonSchmCode: "",
        NominalRate: "7.88",
        NominalSchmCode: "",
        EffectiveRate: "8.5",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Term Deposits  Rates",
    RateCode: "FDEZ",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Sampath Easy FD",
    Comment: "If compunded on daily basis - 4.08%",
    ProductOrder: "11",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "4",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Term Deposits  Rates",
    RateCode: "FDNOR",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Normal Fixed Deposit",
    Comment:
      "SPECIAL OFFER - 3 Months ( 10% ) , 6 Months (8.5%)  Months ( 9.5% ) | Premature Upliftment Rate - 4% p.a | Call deposits - 4 % w.e.f 24/02/2010",
    ProductOrder: "21",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "0",
        MaxContractedMonths: "0",
        Period: "0",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "0",
        MaxContractedMonths: "11",
        Period: "0",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "0",
        MaxContractedMonths: "1",
        Period: "1",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "5.82",
        AerMat: "5.12",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "1",
        MaxContractedMonths: "2",
        Period: "2",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "5",
        AerMat: "5.11",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "2",
        MaxContractedMonths: "5",
        Period: "3",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "7.5",
        AerMat: "7.71",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "5",
        MaxContractedMonths: "6",
        Period: "6",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "8",
        AerMat: "8.16",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "6",
        MaxContractedMonths: "11",
        Period: "7",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "8",
        AerMat: "8.13",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "11",
        MaxContractedMonths: "12",
        Period: "12",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "8.5",
        AerMat: "8.5",
        MatSchmCode: "",
        RateMon: "8.15",
        AerMon: "8.46",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "12",
        MaxContractedMonths: "23",
        Period: "13",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "8.5",
        AerMat: "8.47",
        MatSchmCode: "",
        RateMon: "8.15",
        AerMon: "8.46",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "23",
        MaxContractedMonths: "35",
        Period: "24",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "10.33",
        AerMat: "9.85",
        MatSchmCode: "",
        RateMon: "9.41",
        AerMon: "9.85",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "35",
        MaxContractedMonths: "47",
        Period: "36",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "10.83",
        AerMat: "9.83",
        MatSchmCode: "",
        RateMon: "9.39",
        AerMon: "9.83",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "47",
        MaxContractedMonths: "59",
        Period: "48",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "10.83",
        AerMat: "9.41",
        MatSchmCode: "",
        RateMon: "9",
        AerMon: "9.41",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "59",
        MaxContractedMonths: "999",
        Period: "60",
        PeriodType: "M",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "11.33",
        AerMat: "9.39",
        MatSchmCode: "",
        RateMon: "9",
        AerMon: "9.41",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Term Deposits  Rates",
    RateCode: "FDSAN",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "FD's for Senior Citizens - Sanhinda",
    Comment: "Premature Upliftment Rate 4% p.a",
    ProductOrder: "12",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "0",
        MaxContractedMonths: "11",
        Period: "0",
        PeriodType: "",
        PeriodPicture: "",
        RateMat: "9",
        AerMat: "9",
        MatSchmCode: "",
        RateMon: "8.65",
        AerMon: "9",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "11",
        MaxContractedMonths: "23",
        Period: "1",
        PeriodType: "Y",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "10.83",
        AerMat: "0",
        MatSchmCode: "",
        RateMon: "9.82",
        AerMon: "0",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "23",
        MaxContractedMonths: "35",
        Period: "2",
        PeriodType: "Y",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "11.33",
        AerMat: "0",
        MatSchmCode: "",
        RateMon: "9.76",
        AerMon: "0",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "35",
        MaxContractedMonths: "47",
        Period: "3",
        PeriodType: "Y",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "11.33",
        AerMat: "0",
        MatSchmCode: "",
        RateMon: "9.35",
        AerMon: "0",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "47",
        MaxContractedMonths: "59",
        Period: "4",
        PeriodType: "Y",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "11.83",
        AerMat: "9.74",
        MatSchmCode: "",
        RateMon: "9.3",
        AerMon: "9.74",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "59",
        MaxContractedMonths: "999",
        Period: "5",
        PeriodType: "Y",
        PeriodPicture: "<RI_PERIOD> <RI_PERIOD_TYPE>",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Term Deposits  Rates",
    RateCode: "FDCD",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Certificate of Deposits",
    Comment: "",
    ProductOrder: "13",
    SlabAmount: [
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "0",
        MaxContractedMonths: "5",
        Period: "3",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "7.5",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "5",
        MaxContractedMonths: "6",
        Period: "6",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "8",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "6",
        MaxContractedMonths: "11",
        Period: "7",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "8",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "11",
        MaxContractedMonths: "12",
        Period: "12",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "8.5",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "12",
        MaxContractedMonths: "23",
        Period: "13",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "8.5",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "23",
        MaxContractedMonths: "35",
        Period: "24",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "10.33",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "35",
        MaxContractedMonths: "47",
        Period: "36",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "10.83",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "47",
        MaxContractedMonths: "59",
        Period: "48",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "10.83",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "",
        EndSlbAmount: "",
        SlabPicture: "",
        PerAnumPercentage: "",
        Rate: "",
        RateSchmCode: "",
        MinContractedMonths: "59",
        MaxContractedMonths: "999",
        Period: "60",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "11.33",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Treasury Bills & REPO Rates",
    RateCode: "TBILL",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Treasury Bill Rates",
    Comment: "",
    ProductOrder: "15",
    SlabAmount: [
      {
        BeginSlbAmount: "50000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "7",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "364",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "50000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "5.85",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "91",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.35",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "91",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "1000000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.85",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "91",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "50000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.4",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "182",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.9",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "182",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "1000000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "7.4",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "182",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "7.5",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "364",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "1000000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "8",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "364",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
  {
    ProductMainCategory: "Interest Rates (Local)",
    ProductSubCategory: "Treasury Bills & REPO Rates",
    RateCode: "REPO",
    WithEfectFrom: "5/19/2020 12:00:00 AM",
    ProductHead: "Repo Rates",
    Comment: "",
    ProductOrder: "14",
    SlabAmount: [
      {
        BeginSlbAmount: "10000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "5.25",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "1",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "5.75",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "1",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "1000000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.25",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "1",
        PeriodType: "M",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "10000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "5.85",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "91",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.35",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "91",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "1000000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.85",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "91",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "10000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.4",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "182",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "6.9",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "182",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "1000000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "7.4",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "182",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "10000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "7",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "364",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "500000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "7.5",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "364",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        RATE4: "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
      {
        BeginSlbAmount: "1000000",
        EndSlbAmount: "999999999",
        SlabPicture: "<BEGIN_SLAB_AMT>/- and over",
        PerAnumPercentage: "",
        Rate: "8",
        RateSchmCode: "",
        MinContractedMonths: "",
        MaxContractedMonths: "",
        Period: "364",
        PeriodType: "D",
        PeriodPicture: "",
        RateMat: "",
        AerMat: "",
        MatSchmCode: "",
        RateMon: "",
        AerMon: "",
        MonSchmCode: "",
        NominalRate: "",
        NominalSchmCode: "",
        EffectiveRate: "",
        BON_INT_RATE: "",
        RATE1: "",
        RATE2: "",
        RATE3: "",
        "RAT* Connection #0 to host 192.125.125.43 left intactE4": "",
        RATE5: "",
        DATE1: "",
        DATE2: "",
        DESC1: "",
        DESC2: "",
        DESC: "",
      },
    ],
  },
];
